# 长期记忆候选提取配置。

MEMORY_CANDIDATE_EXTRACT_INTERVAL_TURNS = 5
MEMORY_CANDIDATE_EXTRACT_MIN_CHARS = 50_000
MEMORY_CANDIDATE_EXTRACT_MAX_RETRIES = 3
MEMORY_CANDIDATE_MAX_ITEMS = 20
MEMORY_CANDIDATE_MAX_TEXT_CHARS = 500
MEMORY_CANDIDATE_MAX_EVIDENCE_CHARS = 300
